/// Flutter icons SchoolIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SchoolIcons
///      fonts:
///       - asset: fonts/SchoolIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SchoolIcons {
  SchoolIcons._();

  static const _kFontFam = 'SchoolIcons';
  static const String? _kFontPkg = null;

  static const IconData cheongwon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
